name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thanks for posting your first issue to `kdf`! We appreciate the time you have taken to contribute to this project. Someone will get to your issue soon.'
        pr-message: 'Thanks for posting your first pull request to `kdf`! We appreciate every contribution, big or small, and will try to review your pull request soon.'
